export const EDITOR_DEFAULT_TOOLBAR = `undo redo | blocks | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | template | visualblocks visualchars`;
export const EDITOR_DEFAULT_PLUGINS = [
  "advlist",
  "anchor",
  "autolink",
  "link",
  "code",
  "codesample",
  "lists",
  "charmap",
  "fullscreen",
  "searchreplace",
  "nonbreaking",
  "pagebreak",
  "emoticons",
  "table",
  "preview",
  "quickbars",
  "insertdatetime",
  "visualblocks",
  "visualchars",
  "template",
  "wordcount",
  "help",
];
